### PR TITLE
updating flink version and adding light procedure

### PR DESCRIPTION
**Pull request by robertoNdams**

### CODE REVIEW

**Comment by benjguin** [comment]
Hi, thanks for your contribution. 
I tried running the scenario flink2 with Flink 1.2.

```
docker rmi $BOONTADATA_DOCKER_REGISTRY/boontadata/flinkworker:0.1
docker rmi $BOONTADATA_DOCKER_REGISTRY/boontadata/flinkmaster:0.1
docker rmi $BOONTADATA_DOCKER_REGISTRY/boontadata/flinkbase:0.1
. buildimages.sh
. startscenario.sh flink
. runscenario.sh flink2
``` 

and I get an exception that can be seen in Flink UI for instance: 

```
java.lang.NoClassDefFoundError: com/codahale/metrics/Metric
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1367)
	at com.datastax.driver.core.Cluster.init(Cluster.java:162)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:333)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:308)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:250)
	at org.apache.flink.streaming.connectors.cassandra.CassandraSinkBase.open(CassandraSinkBase.java:67)
	at org.apache.flink.streaming.connectors.cassandra.CassandraTupleSink.open(CassandraTupleSink.java:42)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:112)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:386)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:262)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.Metric
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
![1](https://cloud.githubusercontent.com/assets/929731/24364462/1eab4366-1313-11e7-9482-8614f67e0624.png)

	... 13 more
```

Did you run the scenario successfully and made sure you were in Flink 1.2? 

NB: you may also want to join boontadata.slack.com

:-) 
Benjamin

**Comment by benjguin** [comment]
I worked on the Flink 1.2 in branch `flink3`. 

I included your updates on download from .fr

I will include your pull request by keeping documentation

**Comment by robertoNdams** [comment]
I didn't get no errors with the flink2 scenario having flink1.2. Everything went fine, as expected..
Are you still getting errors ??
[flink2_flink1.2.txt](https://github.com/boontadata/boontadata-streams/files/875515/flink2_flink1.2.txt)

**Comment by benjguin** [comment]
In your log, the final table has all NaN results for m1_sum_downstream. This is because the Flink job has the exception. This could be fixed by changing the pom.xml in flink/master/code. I merged this fix with your pull request in master. 

The exception can be seen from the Flink Dashboard. To see the dashboard, you can create an ssh tunnel to the host (ex: ssh -D 127.0.0.1:8034 myhost....), then use the tunnel as a proxy on your browser (use 127.0.0.1 as a proxy), then browse to http://0.0.0.0:34010.
I'm attaching a screen shot

**Pull request merged**
